### ISSUE TITLE
Add support for sliding sync

### ISSUE THREAD

**Issue by clayrisser** [small-hack/matrix-chart#556]
I get the following error when trying to use the new Element X client.

<a href=https://github.com/small-hack/matrix-chart/assets/6234038/1148aa41-0374-47db-af7c-25f7b5ac17f3>
<img src="https://github.com/small-hack/matrix-chart/assets/6234038/1148aa41-0374-47db-af7c-25f7b5ac17f3" width="300">
</a>

https://element.io/labs/element-x

https://github.com/matrix-org/sliding-sync/blob/main/docs/Landing.md

https://github.com/matrix-org/sliding-sync

**Comment by jessebot** [comment]
Thanks for opening an issue and informing me about this! :)

I think we could setup a helm chart for sliding-sync and then add it to this helm chart as a sub chart here, so it's optional and others can roll their own, since it seems to require it's own database anyway, and this chart already has a postgresql database. Open to suggestions as well.

**Comment by jessebot** [comment]
I started working on the new matrix-sliding-sync helm chart here:
https://github.com/jessebot/matrix-sliding-sync-chart

When it's ready, I'll move it the small-hack org and submit a PR to this repo to add it as a sub chart. ETA is a couple days to a week depending on how much tea I drink :)

**Comment by jessebot** [comment]
Current status is:
- https://github.com/small-hack/matrix-sliding-sync-chart is now available
- I've created a PR on this chart for when it's ready: #560

I'm not sure why, but when I deploy both the sliding-sync chart and the matrix chart from the PR branch, I can't get them to talk to each other. See the the PR for more details on what's been added to this chart, but beyond just the small-hack/matrix-sliding-sync-chart, even when I use the `ghcr.io/matrix-org/sliding-sync:latest` docker container directly, I'm not actually sure what it's supposed to do? Like, which endpoint is supposed to be used? 🤔 I got the [correct json](https://github.com/matrix-org/sliding-sync/blob/main/README.md?plain=1#L51-L61) for requests to https://matrix.example.com/.well-known/matrix/client by using an nginx `ingress` annotation:
  ```yaml
  synapse:
    enabled: true
    ingress:
      enabled: true
      # -- hostname for your synapse server
      host: matrix.example.com
      # -- ingressClassName for the k8s ingress
      className: "nginx"
      tls:
        enabled: true
        secretName: "matrix-tls"
      annotations:
        # -- This annotation is required for the Nginx ingress provider. You can remove it if you use a different ingress provider
        nginx.ingress.kubernetes.io/configuration-snippet: |
          proxy_intercept_errors off;
        cert-manager.io/cluster-issuer: letsencrypt-prod
        # an example for returning the correct json required for syncv3
        nginx.ingress.kubernetes.io/server-snippet: |-
          location = /.well-known/matrix/client {
              return 200 '{"m.homeserver": {"base_url": "https://matrix.example.com"},"org.matrix.msc3575.proxy": {"url": "https://matrix.example.com"}}';
          }
  ```
  
  And I've done a `wget` on that URL to make sure it's working, but I still have no idea how to link these things. @cloudymax has been helping me take a look into it, but if you, @clayrisser, or anyone else knows how to make these two docker images work together even outside of Kubernetes, I can make it work in k8s. Sliding Sync hasn't got a lot of docs though 🤷 (happy to help change that upstream as well if I figure out what I'm doing)
