### ISSUE TITLE
M_UNKNOWN_TOKEN: Invalid access token passed when SSO with mas

### ISSUE THREAD

**Issue by clayrisser** [small-hack/matrix-chart#677]
When using mas with upstream_oauth2 I get the following error.

```
Unexpected error

Homeserver connection error

HomeserverConnection(Failed to query localpart availability from Synapse

Caused by:
    request failed with status 401 Unauthorized: M_UNKNOWN_TOKEN: Invalid access token passed.)
```

![Image](https://github.com/user-attachments/assets/aa51acdf-3182-4212-9924-81ccb2ab1a05)

**Comment by clayrisser** [comment]
The issue is because msc3861 needs to be enabled.

```yaml
matrix:
  experimental_features:
    msc3861:
      enabled: true
```
